GET http://localhost:8080/currency_exchange_war/currencies

###

GET http://localhost:8080/currency_exchange_war/currencies/

###

GET http://localhost:8080/currency_exchange_war/currencies/US

###

GET http://localhost:8080/currency_exchange_war/currencies/USD

###

GET http://localhost:8080/currency_exchange_war/currencies/USDD

###
