GET http://localhost:8080/currency_exchange_war/currencies

###

GET http://localhost:8080/currency_exchange_war/currency/

###

GET http://localhost:8080/currency_exchange_war/currency/US

###

GET http://localhost:8080/currency_exchange_war/currency/BTC

###

GET http://localhost:8080/currency_exchange_war/currency/USDD

###

POST http://localhost:8080/currency_exchange_war/currencies

baseCurrencyCode:BYN
targetCurrencyCode:RUB
rate:40
###